/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse200 struct {

	MaterialInstance MaterialInstance `json:"materialInstance,omitempty"`

	MaterialInstanceHistory []MaterialInstanceHistory `json:"materialInstanceHistory,omitempty"`
}
