/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Comment - comments that are made on materials during review
type Comment struct {
	Id int32 `json:"id,omitempty" gorm:"column:id"`

	Content string `json:"content,omitempty" gorm:"column:content"`

	MaterialInstanceId int32 `json:"materialInstanceId,omitempty" gorm:"column:materialInstanceId"`

	ReviewerId int32 `json:"reviewerId,omitempty" gorm:"column:reviewerId"`

	CommentDate string `json:"commentDate,omitempty" gorm:"column:commentDate"`
}

func (b *Comment) TableName() string {
	return "comment"
}
