/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Store - Store metadata for each individual Aesop store
type Store struct {
	Id int32 `json:"id,omitempty" gorm:"column:id"`

	StoreName string `json:"storeName,omitempty" gorm:"column:storeName"`

	Country string `json:"country,omitempty" gorm:"column:country"`

	ScorecardType string `json:"scorecardType,omitempty" gorm:"column:scorecardType"`

	LocationType string `json:"locationType,omitempty" gorm:"column:locationType"`

	RoicCapex string `json:"roicCapex,omitempty" gorm:"column:roicCapex"`

	Currency string `json:"currency,omitempty" gorm:"column:currency"`

	LeaseTermInYears float32 `json:"leaseTermInYears,omitempty" gorm:"column:leaseTermInYears"`

	ProjectManagerId int32 `json:"projectManagerId,omitempty" gorm:"column:projectManagerId"`

	ArchitectId int32 `json:"architectId,omitempty" gorm:"column:architectId"`

	ContractorId string `json:"contractorId,omitempty" gorm:"column:contractorId"`

	SignedCoc bool `json:"signedCoc,omitempty" gorm:"column:signedCoc"`

	SignedNda bool `json:"signedNda,omitempty" gorm:"column:signedNda"`

	TotalSqm float32 `json:"totalSqm,omitempty" gorm:"column:totalSqm"`

	RetailSqm float32 `json:"retailSqm,omitempty" gorm:"column:retailSqm"`

	BohSqm float32 `json:"bohSqm,omitempty" gorm:"column:bohSqm"`

	MarketingMediaType string `json:"marketingMediaType,omitempty" gorm:"column:marketingMediaType"`

	Pos float32 `json:"pos,omitempty" gorm:"column:pos"`

	Mpos float32 `json:"mpos,omitempty" gorm:"column:mpos"`

	TapNumber int32 `json:"tapNumber,omitempty" gorm:"column:tapNumber"`

	TreatmentSpace bool `json:"treatmentSpace,omitempty" gorm:"column:treatmentSpace"`

	Bathroom bool `json:"bathroom,omitempty" gorm:"column:bathroom"`

	OtherSpace string `json:"otherSpace,omitempty" gorm:"column:otherSpace"`

	ReviewerId int32 `json:"reviewerId,omitempty" gorm:"column:reviewerId"`

	ReviewRequired int32 `json:"reviewRequired,omitempty" gorm:"column:reviewRequired"`

	Region string `json:"region,omitempty" gorm:"column:region"`

	SusInitGreenspace bool `json:"susInitGreenspace,omitempty" gorm:"column:susInitGreenspace"`

	SusInitRainwater bool `json:"susInitRainwater,omitempty" gorm:"column:susInitRainwater"`

	SusInitSolarPV bool `json:"susInitSolarPV,omitempty" gorm:"column:susInitSolarPV"`

	SusInitGreywater bool `json:"susInitGreywater,omitempty" gorm:"column:susInitGreywater"`

	SusInitBattery bool `json:"susInitBattery,omitempty" gorm:"column:susInitBattery"`

	SusInitVentilation bool `json:"susInitVentilation,omitempty" gorm:"column:susInitVentilation"`

	SusInitComposting bool `json:"susInitComposting,omitempty" gorm:"column:susInitComposting"`

	StoreStatus string `json:"storeStatus,omitempty" gorm:"column:storeStatus"`

	CreatorId int32 `json:"creatorId,omitempty" gorm:"column:creatorId"`

	ReviewComment string `json:"reviewComment,omitempty" gorm:"column:reviewComment"`

	CatCSFScore float32 `json:"catCSFScore,omitempty" gorm:"column:catCSFScore"`

	CatMUScore float32 `json:"catMUScore,omitempty" gorm:"column:catMUScore"`

	CatFFScore float32 `json:"catFFScore,omitempty" gorm:"column:catFFScore"`

	SubCatFlooringScore float32 `json:"subCatFlooringScore,omitempty" gorm:"column:subCatFlooringScore"`

	SubCatWallScore float32 `json:"subCatWallScore,omitempty" gorm:"column:subCatWallScore"`

	SubCatCeilingScore float32 `json:"subCatCeilingScore,omitempty" gorm:"column:subCatCeilingScore"`

	SubCatFacadeScore float32 `json:"subCatFacadeScore,omitempty" gorm:"column:subCatFacadeScore"`

	SubCatPOSScore float32 `json:"subCatPOSScore,omitempty" gorm:"column:subCatPOSScore"`

	SubCatProdShelvingScore float32 `json:"subCatProdShelvingScore,omitempty" gorm:"column:subCatProdShelvingScore"`

	SubCatBOHScore float32 `json:"subCatBOHScore,omitempty" gorm:"column:subCatBOHScore"`

	SubCatBasinScore float32 `json:"subCatBasinScore,omitempty" gorm:"column:subCatBasinScore"`

	SubCatFurnitureScore float32 `json:"subCatFurnitureScore,omitempty" gorm:"column:subCatFurnitureScore"`

	SubCatLightingScore float32 `json:"subCatLightingScore,omitempty" gorm:"column:subCatLightingScore"`

	SubCatFixturesScore float32 `json:"subCatFixturesScore,omitempty" gorm:"column:subCatFixturesScore"`

	TotalScore float32 `json:"totalScore,omitempty" gorm:"column:totalScore"`
}

func (b *Store) TableName() string {
	return "store"
}
