/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MaterialInstanceHistory struct {
	Id int32 `json:"id,omitempty" gorm:"column:id"`

	MaterialInstanceId int32 `json:"materialInstanceId,omitempty" gorm:"column:materialInstanceId"`

	SnapshotDate string `json:"snapshotDate,omitempty" gorm:"column:snapshotDate"`

	CreatedDate string `json:"createdDate,omitempty" gorm:"column:createdDate"`

	Unit string `json:"unit,omitempty" gorm:"column:unit"`

	MaterialQuantity float32 `json:"materialQuantity,omitempty" gorm:"column:materialQuantity"`

	MaterialStatus string `json:"materialStatus,omitempty" gorm:"column:materialStatus"`

	OriginId int32 `json:"originId,omitempty" gorm:"column:originId"`
}

func (b *MaterialInstanceHistory) TableName() string {
	return "materialInstanceHistory"
}
