/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {

	// Unique identifier for the given user.
	Id int32 `json:"id" gorm:"column:id"`

	Email string `json:"email" gorm:"column:email"`

	DisplayName string `json:"displayName" gorm:"column:displayName"`

	// The date that the user was created.
	CreatedDate string `json:"createdDate" gorm:"column:createdDate"`

	AccessLevel string `json:"accessLevel" gorm:"column:accessLevel"`
}

func (b *User) TableName() string {
	return "user"
}
