/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// EpicMaterial - Material metadata
type EpicMaterial struct {

	Id int32 `json:"id,omitempty"`

	Category string `json:"category,omitempty"`

	Type string `json:"type,omitempty"`

	Material string `json:"material,omitempty"`

	FunctionalUnit string `json:"functionalUnit,omitempty"`

	EmbodiedEnergy float32 `json:"embodiedEnergy,omitempty"`

	EmbodiedWater float32 `json:"embodiedWater,omitempty"`

	EmbodiedGHGE float32 `json:"embodiedGHGE,omitempty"`

	MoreInformationUrl string `json:"moreInformationUrl,omitempty"`
}
