/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MaterialInstance struct {

	Id int32 `json:"id,omitempty"`

	MaterialTypeId int32 `json:"materialTypeId,omitempty"`

	MaterialStatus string `json:"materialStatus,omitempty"`

	MaterialQuantity float32 `json:"materialQuantity,omitempty"`

	Unit string `json:"unit,omitempty"`

	CreatedDate string `json:"createdDate,omitempty"`

	SupplierLocation string `json:"supplierLocation,omitempty"`

	ManufacturerLocation string `json:"manufacturerLocation,omitempty"`

	SupplierName string `json:"supplierName,omitempty"`

	ManufacturerName string `json:"manufacturerName,omitempty"`

	PrimaryTransportMethod string `json:"primaryTransportMethod,omitempty"`

	OriginId int32 `json:"originId,omitempty"`

	StoreId int32 `json:"storeId,omitempty"`
}
