/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type User struct {

	// Unique identifier for the given user.
	Id int32 `json:"id"`

	Email string `json:"email"`

	// The date that the user was created.
	CreatedDate string `json:"createdDate,omitempty"`

	AccessLevel string `json:"accessLevel"`
}
