/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Comment - comments that are made on materials during review
type Comment struct {

	Id int32 `json:"id,omitempty"`

	Content string `json:"content,omitempty"`

	MaterialInstanceId int32 `json:"materialInstanceId,omitempty"`

	ReviewerId int32 `json:"reviewerId,omitempty"`

	CommentDate string `json:"commentDate,omitempty"`
}
