/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// EpicMaterial - Material metadata
type Certification struct {
	Id int32 `json:"id,omitempty" gorm:"column:id"`

	EcoLabel string `json:"ecoLabel,omitempty" gorm:"column:ecoLabel"`

	Description string `json:"description,omitempty" gorm:"column:description"`

	MaterialCategory string `json:"materialCategory,omitempty" gorm:"column:materialCategory"`

	Region string `json:"region,omitempty" gorm:"column:region"`

	Country string `json:"country,omitempty" gorm:"column:country"`

	Value int32 `json:"value,omitempty" gorm:"column:value"`

	Prompt string `json:"prompt,omitempty" gorm:"column:prompt"`

	Link string `json:"link,omitempty" gorm:"column:link"`
}

func (b *Certification) TableName() string {
	return "certification"
}
