/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Store - Store metadata for each individual Aesop store
type Store struct {

	Id int32 `json:"id,omitempty"`

	StoreName string `json:"storeName,omitempty"`

	Country string `json:"country,omitempty"`

	ScorecardType string `json:"scorecardType,omitempty"`

	LocationType string `json:"locationType,omitempty"`

	RoicCapex string `json:"roicCapex,omitempty"`

	Currency string `json:"currency,omitempty"`

	LeaseTermInYears float32 `json:"leaseTermInYears,omitempty"`

	ProjectManagerId int32 `json:"projectManagerId,omitempty"`

	ArchitectId int32 `json:"architectId,omitempty"`

	ContractorId int32 `json:"contractorId,omitempty"`

	SignedCoc bool `json:"signedCoc,omitempty"`

	SignedNda bool `json:"signedNda,omitempty"`

	TotalSqm float32 `json:"totalSqm,omitempty"`

	RetailSqm float32 `json:"retailSqm,omitempty"`

	BohSqm float32 `json:"bohSqm,omitempty"`

	MarketingMediaType string `json:"marketingMediaType,omitempty"`

	PosSqm float32 `json:"posSqm,omitempty"`

	MposSqm float32 `json:"mposSqm,omitempty"`

	TapNumber int32 `json:"tapNumber,omitempty"`

	TreatmentSpace bool `json:"treatmentSpace,omitempty"`

	Bathroom bool `json:"bathroom,omitempty"`

	OtherSpace string `json:"otherSpace,omitempty"`

	ReviewerId int32 `json:"reviewerId,omitempty"`

	ReviewRequired int32 `json:"reviewRequired,omitempty"`
}
