/*
 * scorecard
 *
 * inital pass at scorecard API
 *
 * API version: 1.0
 * Contact: mitchell.harvey@arup.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MaterialType struct {

	Id int32 `json:"id,omitempty"`

	Category string `json:"category,omitempty"`

	SubCategory string `json:"subCategory,omitempty"`

	ItemType string `json:"itemType,omitempty"`

	RawMaterial string `json:"rawMaterial,omitempty"`

	EndOfLifeAssessment string `json:"endOfLifeAssessment,omitempty"`

	ProductCertification string `json:"productCertification,omitempty"`
}
